[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
